### ISSUE TITLE
Crash starting server

### ISSUE THREAD

**Issue by coryshain** [lil-lab/cb2#1]
I followed all the setup steps in the readme (I think) with no errors, but when I run the following to start the server:

    python3 -m server.main --config_filepath="server/config/local-config.yaml"

I get this error:

    python3 -m server.main --config_filepath="server/config/local-config.yaml"
    [2023-05-11 12:00:03,354] server.config.config INFO [config:ValidateConfig:47] //////////////// Created data directory /home/corys/.local/share/cb2-game-dev ////////////////
    [2023-05-11 12:00:03,354] server.config.config WARNING [config:ValidateConfig:52] Record directory /home/corys/.local/share/cb2-game-dev/game_data.db does not exist. This can happen if it's your first time running a new config. The program will just create a database for you.
    [2023-05-11 12:00:03,354] server.config.config WARNING [config:ValidateConfig:57] Record directory /home/corys/.local/share/cb2-game-dev/game_records does not exist. This is okay, it's just a sign that the logged network packets may be missing. Or it's your first time running a config.
    [2023-05-11 12:00:03,354] root INFO [main:main:1384] Config file parsed.
    [2023-05-11 12:00:03,354] root INFO [main:main:1385] data prefix:
    [2023-05-11 12:00:03,354] root INFO [main:main:1386] Log directory: /home/corys/.local/share/cb2-game-dev/game_records
    [2023-05-11 12:00:03,354] root INFO [main:main:1387] Assets directory: /home/corys/.local/share/cb2-game-dev/assets
    [2023-05-11 12:00:03,354] root INFO [main:main:1388] Database path: /home/corys/.local/share/cb2-game-dev/game_data.db
    [2023-05-11 12:00:03,363] server.schemas.base INFO [base:SetDatabase:30] Pragmas: [['journal_mode', 'wal'], ['cache_size', -1048576], ['foreign_keys', '1'], ['synchronous', 'off']]
    [2023-05-11 12:00:03,376] root INFO [main:main:1405] WARNING:
    Traceback (most recent call last):
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 557, in __init__
        raise ValueError("Not a directory")
    ValueError: Not a directory
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/corys/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/home/corys/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/home/corys/cb2/server/main.py", line 1432, in <module>
        fire.Fire(main)
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
        component_trace = _Fire(component, args, parsed_flag_args, context, name)
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
        component, remaining_args = _CallAndUpdateTrace(
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
        component = fn(*varargs, **kwargs)
      File "/home/corys/cb2/server/main.py", line 1415, in main
        loop.run_until_complete(tasks)
      File "/home/corys/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/home/corys/cb2/server/main.py", line 1290, in serve
        app.add_routes(routes)
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_app.py", line 334, in add_routes
        return self.router.add_routes(routes)
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 1200, in add_routes
        registered_routes.extend(route_def.register(self))
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_routedef.py", line 98, in register
        resource = router.add_static(self.prefix, self.path, **self.kwargs)
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 1124, in add_static
        resource = StaticResource(
      File "/home/corys/cb2/cb2/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 559, in __init__
        raise ValueError(f"No directory exists at '{directory}'") from error
    ValueError: No directory exists at '/home/corys/cb2/server/www/WebGL'

Any thoughts?

**Comment by jsharf** [comment]
On my phone, but it looks like you need to have the client-side downloaded.
This is the game front-end, which is compiled into an HTML file and some
static assets at server/www/WebGL. I may have forgotten to add this to the
setup instructions. This is compiled in Unity, so to save you the trouble
of installing unity, I provide compiled releases of it.

For now, download the 1.0.0 release WebGL.zip file and extract it to
server/www.

https://github.com/lil-lab/cb2/releases/tag/deployed-march-2023

I have since made some changes to the codebase. The client might be a bit
outdated, but it should work with most features. A new release may be in
order…

I’m free today to videochat to resolve any further issues you have in
setting up the repository. Feel free to email me if you have any questions!
