### ISSUE TITLE
 Using Pretrained Models error

### ISSUE THREAD

**Issue by Yang011013** [lil-lab/cb2#4]
**when I run this command:**
python -m follower_bots.training.follower_demo --host=http://localhost:8080/ --experiments_folder=./follower_bots/experiments/pretraining/deployment_models --experiments_name run_3
**error:**
pygame 2.1.2 (SDL 2.0.18, Python 3.9.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Anaconda\envs\cb2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda\envs\cb2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\keyang\Desktop\yan0\Agent\cb2\follower_bots\training\follower_demo.py", line 15, in <module>
    from follower_bots.data_utils.pyclient_utils import (
  File "C:\Users\keyang\Desktop\yan0\Agent\cb2\follower_bots\data_utils\pyclient_utils.py", line 30, in <module>
    from py_client.endpoint_pair import EndpointPair
ModuleNotFoundError: No module named 'py_client.endpoint_pair'

**Comment by jsharf** [comment]
Ah -- There's two things going on here. Looks like the follower_bots/ directory is behind, as there was a large refactor.

1. py_client is now pyclient.
2. Imports should now be global (from cb2game.pyclient import endpoint_pair).

#2 in that list might not be necessary, depending on repo setup.

I'll look into fixing this later, but if you want a quick fix locally, this should help!

**Comment by Yang011013** [comment]
Thanks, problem solved
