### ISSUE TITLE
peewee.InterfaceError: Error, database must be initialized before opening a connection

### ISSUE THREAD

**Issue by Yang011013** [lil-lab/cb2#5]
when I try to train a new model by running this command:`python -m follower_bots.data_utils.preprocess_sql`, error occurred `
pygame 2.1.2 (SDL 2.0.18, Python 3.9.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
Record directory follower_bots\pretraining_data\game_records does not exist. This is okay, it's just a sign that the logged network packets may be missing. Or it's your first time running a config.
Reading database from follower_bots\pretraining_data\game_data.db
Traceback (most recent call last):
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3158, in execute_sql
    cursor = self.cursor(commit)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3142, in cursor
    self.connect()
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3087, in connect
    raise InterfaceError('Error, database must be initialized '
peewee.InterfaceError: Error, database must be initialized before opening a connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\envs\cb2\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda\envs\cb2\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\keyang\Desktop\yan0\Agent\cb2\follower_bots\data_utils\preprocess_sql.py", line 541, in <module>
    main()
  File "C:\Users\keyang\Desktop\yan0\Agent\cb2\follower_bots\data_utils\preprocess_sql.py", line 531, in main
    base.CreateTablesIfNotExists(server.schemas.defaults.ListDefaultTables())
  File "C:\Users\keyang\Desktop\yan0\Agent\cb2\server\schemas\base.py", line 61, in CreateTablesIfNotExists
    database.create_tables(tables)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3348, in create_tables
    model.create_table(**options)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 6721, in create_table
    cls._schema.create_all(safe, **options)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 5828, in create_all
    self.create_table(safe, **table_options)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 5683, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3167, in execute_sql
    self.commit()
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3158, in execute_sql
    cursor = self.cursor(commit)
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3142, in cursor
    self.connect()
  File "C:\Anaconda\envs\cb2\lib\site-packages\peewee.py", line 3087, in connect
    raise InterfaceError('Error, database must be initialized '
peewee.InterfaceError: Error, database must be initialized before opening a connection.
`

I'm sure game_data.db is in the pretraining_data folder. 
<img width="475" alt="Snipaste_2024-03-03_16-35-34" src="https://github.com/lil-lab/cb2/assets/76615593/22de5ecf-cfcd-4e12-a6dd-74d4a886274d">

**Comment by jsharf** [comment]
I think I see what's going on. We migrated DB schemas at some point, and so the default list of tables:

TABLES = [
    CardSets,
    Card,
    CardSelections,
    Remote,
    ConnectionEvents,
    Game,
    Turn,
    Instruction,
    Move,
    LiveFeedback,
    InitialState,
    MapUpdate,
    PropUpdate,
    Worker,
    Assignment,
    WorkerExperience,
    Leaderboard,
    Username,
    GoogleUser,
    Event,
    ClientException,
]

includes both old and new tables. You're running the new software so you only have the new tables. The line

base.CreateTablesIfNotExists(server.schemas.defaults.ListDefaultTables())

Tries to create the old tables (which would be empty and useless). It shouldn't do that in your case. As a workaround, I recommend creating empty tables of those names using the Sql db browser. Or you could contribute to CB2! Modify src/cb2game/server/schemas/defaults.py to have OLD_TABLES and TABLES, and the new tables should only be the tables *currently* used (check your DB before modifying it for a list). Then make ListDefaultTables only return the new list.

I'm no longer working on this project full time, so there might be some delays in response, but I'll try to get back to you sometime this week.

Can you include your config file, and also manually browse your DB to tell me what tables are there?
